[package]
name = "diopser"
version = "0.4.0"
edition = "2021"
authors = ["LogicCuteGuy <contact@logiccuteguy.com>", "Robbert van der Helm <mail@robbertvanderhelm.nl>"]
license = "GPL-3.0-or-later"
homepage = "https://github.com/LogicCuteGuy/logic_nih_plug/tree/master/plugins/diopser"

[lib]
crate-type = ["cdylib"]

[features]
default = ["simd"]
# Make it go fast, vroom. Requires a nightly compiler. Support for the non-SIMD
# version has been removed at the moment.
simd = ["logic_nih_plug/simd"]

[dependencies]
logic_nih_plug = { path = "../../", features = ["assert_process_allocs"] }
logic_nih_plug_vizia = { path = "../../logic_nih_plug_vizia" }

atomic_float = "1.1"
semver = "1.0.28"

# For the GUI
realfft = "3.5"
open = "5.3"
triple_buffer = "9.0"
