//! Build script for nih_plug_juce.
//!
//! This build script is responsible for:
//! - Detecting the platform (Windows, macOS, Linux)
//! - Configuring CMake to build JUCE modules
//! - Setting up platform-specific compiler flags
//! - Linking JUCE libraries into the Rust binary

use std::env;
use std::path::PathBuf;

fn main() {
    // Detect platform
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap();
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap();
    
    println!("cargo:warning=Building nih_plug_juce for {} on {}", target_os, target_arch);
    
    // Get the path to the JUCE directory (relative to workspace root)
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let workspace_root = manifest_dir.parent().unwrap();
    let juce_path = workspace_root.join("JUCE");
    
    // Verify JUCE exists
    if !juce_path.exists() {
        panic!(
            "JUCE directory not found at {:?}. Please ensure JUCE is available in the workspace root.",
            juce_path
        );
    }
    
    // Configure and build JUCE using CMake
    let mut cmake_config = cmake::Config::new("cpp");
    
    // Set JUCE path
    cmake_config.define("JUCE_SOURCE_DIR", juce_path.to_str().unwrap());
    
    // Configure JUCE to only build modules (no examples, extras, etc.)
    cmake_config.define("JUCE_MODULES_ONLY", "ON");
    cmake_config.define("JUCE_BUILD_EXAMPLES", "OFF");
    cmake_config.define("JUCE_BUILD_EXTRAS", "OFF");
    
    // Set C++ standard
    cmake_config.define("CMAKE_CXX_STANDARD", "17");
    cmake_config.define("CMAKE_CXX_STANDARD_REQUIRED", "ON");
    
    // Platform-specific configuration
    match target_os.as_str() {
        "macos" => {
            cmake_config.define("CMAKE_OSX_DEPLOYMENT_TARGET", "10.13");
            // Use libc++ on macOS
            cmake_config.cxxflag("-stdlib=libc++");
        }
        "linux" => {
            // Enable position-independent code
            cmake_config.cflag("-fPIC");
            cmake_config.cxxflag("-fPIC");
        }
        "windows" => {
            // Windows-specific configuration
        }
        _ => {
            println!("cargo:warning=Unsupported platform: {}", target_os);
        }
    }
    
    // Build the JUCE bridge library
    let dst = cmake_config.build();
    
    // Link the JUCE bridge library
    // The cmake crate puts the build output in build/lib, not lib
    println!("cargo:rustc-link-search=native={}/build/lib", dst.display());
    println!("cargo:rustc-link-lib=static=nih_plug_juce_bridge");
    
    // Build the cxx bridge
    // This compiles the Rust-C++ bridge code generated by the cxx crate
    let mut cxx_builder = cxx_build::bridge("src/bridge.rs");
    
    // Add the C++ bridge source files
    cxx_builder.file("cpp/juce_bridge.cpp");
    cxx_builder.file("cpp/component_bridge.cpp");
    
    // Set C++ standard
    cxx_builder.flag_if_supported("-std=c++17");
    cxx_builder.flag_if_supported("/std:c++17");
    
    // Add include directories
    cxx_builder.include("cpp");
    cxx_builder.include(juce_path.join("modules"));
    
    // Ensure debug/release mode consistency with JUCE
    // JUCE requires all compilation units to be built in the same mode
    let profile = env::var("PROFILE").unwrap();
    if profile == "debug" {
        cxx_builder.define("DEBUG", "1");
        cxx_builder.define("_DEBUG", "1");
    } else {
        cxx_builder.define("NDEBUG", "1");
    }
    
    // Platform-specific flags
    match target_os.as_str() {
        "macos" => {
            cxx_builder.flag("-stdlib=libc++");
        }
        "linux" => {
            cxx_builder.flag("-fPIC");
        }
        _ => {}
    }
    
    // Compile the cxx bridge
    cxx_builder.compile("nih_plug_juce_cxx_bridge");
    
    // Platform-specific system library linking
    match target_os.as_str() {
        "macos" => {
            // macOS frameworks required by JUCE
            println!("cargo:rustc-link-lib=framework=Cocoa");
            println!("cargo:rustc-link-lib=framework=CoreFoundation");
            println!("cargo:rustc-link-lib=framework=CoreGraphics");
            println!("cargo:rustc-link-lib=framework=CoreText");
            println!("cargo:rustc-link-lib=framework=IOKit");
            println!("cargo:rustc-link-lib=framework=QuartzCore");
            println!("cargo:rustc-link-lib=framework=Accelerate");
            println!("cargo:rustc-link-lib=framework=WebKit");
            println!("cargo:rustc-link-lib=framework=DiscRecording");
            println!("cargo:rustc-link-lib=c++");
        }
        "linux" => {
            // Linux libraries required by JUCE
            println!("cargo:rustc-link-lib=X11");
            println!("cargo:rustc-link-lib=Xext");
            println!("cargo:rustc-link-lib=Xinerama");
            println!("cargo:rustc-link-lib=Xrandr");
            println!("cargo:rustc-link-lib=Xcursor");
            println!("cargo:rustc-link-lib=freetype");
            println!("cargo:rustc-link-lib=fontconfig");
            println!("cargo:rustc-link-lib=pthread");
            println!("cargo:rustc-link-lib=dl");
            println!("cargo:rustc-link-lib=stdc++");
        }
        "windows" => {
            // Windows libraries required by JUCE
            println!("cargo:rustc-link-lib=gdi32");
            println!("cargo:rustc-link-lib=user32");
            println!("cargo:rustc-link-lib=comdlg32");
            println!("cargo:rustc-link-lib=ole32");
            println!("cargo:rustc-link-lib=oleaut32");
            println!("cargo:rustc-link-lib=uuid");
            println!("cargo:rustc-link-lib=winmm");
            println!("cargo:rustc-link-lib=version");
            println!("cargo:rustc-link-lib=shlwapi");
            println!("cargo:rustc-link-lib=wininet");
        }
        _ => {}
    }
    
    // Tell cargo to rerun this build script if any of these change
    println!("cargo:rerun-if-changed=cpp/CMakeLists.txt");
    println!("cargo:rerun-if-changed=cpp/juce_bridge.h");
    println!("cargo:rerun-if-changed=cpp/juce_bridge.cpp");
    println!("cargo:rerun-if-changed=cpp/component_bridge.cpp");
    println!("cargo:rerun-if-changed=cpp/path_bridge.cpp");
    println!("cargo:rerun-if-changed=src/bridge.rs");
    println!("cargo:rerun-if-changed=build.rs");
}
