[package]
name = "soft_vacuum"
version = "0.1.0"
edition = "2021"
authors = ["LogicCuteGuy <contact@logiccuteguy.com>", "Robbert van der Helm <mail@robbertvanderhelm.nl>"]
license = "GPL-3.0-or-later"
homepage = "https://github.com/LogicCuteGuy/logic_nih_plug/tree/master/plugins/soft_vacuum"

[lib]
crate-type = ["cdylib"]

[dependencies]
logic_nih_plug = { path = "../../", features = ["assert_process_allocs"] }

[dev-dependencies]
approx = "0.5.1"
