[package]
name = "nih_plug_osc"
version = "0.0.0"
edition = "2021"
rust-version = "1.80"
authors = ["Robbert van der Helm <mail@robbertvanderhelm.nl>"]
license = "ISC"

keywords = ["osc", "networking", "opensoundcontrol"]
description = "Open Sound Control support ported from JUCE for nih-plug"
repository = "https://github.com/robbert-vdh/nih-plug"

[features]
default = ["sender", "receiver"]
sender = []
receiver = []
bundles = []
full = ["sender", "receiver", "bundles"]

[dependencies]
thiserror = "1.0"

[dev-dependencies]
proptest = "1.4"
