[package]
name = "gain_multi_format"
version = "0.1.0"
edition = "2021"
authors = ["LogicCuteGuy <contact@logiccuteguy.com>", "Robbert van der Helm <mail@robbertvanderhelm.nl>"]
license = "ISC"
description = "Minimal gain plugin exported in VST3, CLAP, AU, AUv3, LV2, AAX, and VST2 simultaneously"

[lib]
crate-type = ["cdylib"]

[dependencies]
logic_nih_plug = { path = "../../../", features = ["vst2", "vst3", "au", "auv3", "lv2"] }
