[package]
name = "sine"
version = "0.1.0"
edition = "2021"
authors = ["LogicCuteGuy <contact@logiccuteguy.com>", "Robbert van der Helm <mail@robbertvanderhelm.nl>"]
license = "ISC"
description = "Pure sine wave generator plugin"

[lib]
crate-type = ["cdylib"]

[dependencies]
logic_nih_plug = { path = "../../../", features = ["assert_process_allocs"] }
