[package]
name = "gain"
version = "0.1.0"
edition = "2021"
authors = ["LogicCuteGuy <contact@logiccuteguy.com>", "Robbert van der Helm <mail@robbertvanderhelm.nl>"]
license = "ISC"
description = "The smallest possible logic_nih_plug plugin: a smoothed FloatParam with no editor"

[lib]
crate-type = ["cdylib"]

[dependencies]
logic_nih_plug = { path = "../../../", features = ["assert_process_allocs"] }

parking_lot = "0.12"
